### PR TITLE
Add python 2.7 support

### PR DESCRIPTION
**Pull request by ecarreras**
Add python 2.7 support

### CODE REVIEW

**Comment by trarbr** [comment]
Thanks for submitting your PR, I'll have a look at it on Friday

**Comment by trarbr** [comment]
I looked it over. I'm not really happy about the ``if`` around the super calls, but I guess it might be necessary. I tried doing ``super(BuildHTTPServer, self).__init__(server_address, handler_class)`` instead, but this fails on python2 since HTTPServer is an old-style class.

Anyway, thanks for the contribution! sphinxview has been long neglected, but I have some changes I'd like to make. I'll merge your PR this weekend or next week, and make a new release next weekend.

**Comment by ecarreras** [comment]
> I looked it over. I'm not really happy about the if around the super calls, but I guess it might be necessary. I tried doing super(BuildHTTPServer, self).__init__(server_address, handler_class) instead, but this fails on python2 since HTTPServer is an old-style class.

The other way is using old style in everywhere. Python3 supports it too.

**Comment by trarbr** [comment]
True. Well, I think we should keep the ``if`` anyway. It's not really a problem when it's just three places, and then it's explicit that we're using the base class directly for compatibility reasons. Thanks!

**Pull request merged**
